---
- name: setup shipping
  hosts: shipping.devops-project.co.uk
  become: yes

  tasks:
   - name: install maven
     ansible.builtin.package:
       name: " {{ item }} "
       state: present
     loop:
      - maven
      - mysql

   - name: install mysql
     ansible.builtin.pip:
       executable: pip3.9
       name: "{{ item }}"
     loop:
      - pymysql
      - cryptography

   - name: craete user
     ansible.builtin.user:
       name: roboshop
       state: present
       system: true
       comment: sys user
       home: /app
       shell: /sbin/nologin

   - name: craete folder
     ansible.builtin.file:
       path: /app
       state: directory

   - name: download code
     ansible.builtin.get_url:
       url: "https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip"
       dest: /tmp/shipping.zip

   - name: unzip code
     ansible.builtin.unarchive:
       src: /tmp/shipping.zip
       dest: /app
       remote_src: yes
      
   - name: install dependecies
     ansible.builtin.command: mvn clean package
     args:
       chdir: /app

   - name: rename file
     ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
     args:
       chdir: /app

   - name: craete systemd service
     ansible.builtin.copy:
       src: shipping.service
       dest: /etc/systemd/system/shipping.service

   - name: load database
     community.mysql.mysql_db:
       state: import
       name: all
       login_host: mysql.devops-project.co.uk
       login_user: root
       login_password: RoboShop@1
       target: "{{ item }}"
     loop:
       - /app/db/schema.sql
       - /app/db/app-user.sql
       - /app/db/master-data.sql

   - name: start service
     ansible.built.systemd_service:
       name: shipping
       daemon-reload: true
       state: started
       enabled: yes
       

    