---
- name: setup user
  hosts: user.devops-project.co.uk
  become: yes

  tasks:
   - name: diasble nidejs
     ansible.builtin.command: dnf module diasbale nodejs -y
     
   - name: enable nodejs
     ansible.builtin.command: dnf module enable nodejs:20 -y

   - name: install nodejs
     ansible.builtin.package:
       name: nodejs
       state: present

   - name: create user
     ansible.builtin.user:
       name: roboshop
       state: present
       system: true
       comment: system user
       home: /app
       shell: /sbin/nologin

   - name: create folder
     ansible.builtin.file:
       path: /app
       state: directory

   - name: download code
     ansible.builtin.get_url:
       url: "https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip"
       dest: /tmp/user.zip

   - name: unzip
     ansible.builtin.unarchive:
       src: /tmp/user.zip
       dest: /app

   - name: install dependencies
     ansible.builtin.npm:
       path: /app
       state: present

   - name: craete systemd service
     ansible.builtin.copy:
       src: user.service
       dest: /etc/systemd/system/user.service

   - name: start and enable service
     ansible.builtin.systemd_service:
       name: user
       state: started
       daemon-reload: true
       enabled: yes

   - name: check user
     ansible.builtin.command: curl http://user.devops-project.co.uk:8080/health
     register: user

   - name: print sttaus
     ansible.builtin.debug:
       msg: "{{ user }}"